#!/bin/bash
# exit on error
set -e
# Start point
openwrt_dir="$( cd `dirname "${BASH_SOURCE[0]}"` && pwd )"
spec_dir="${openwrt_dir}/specs"

# Utilities
function print_usage() {
  echo -e "Usage:\n    $(basename "${BASH_SOURCE[0]}") <spec>"
  echo "Note: <spec> SHOULD be defined in specs folder."
  [ -d ${spec_dir} ] && echo "Current specs := $(cd "${spec_dir}"; echo *)"
}
function check_hash() {
  cmd=sha256sum
  which sha256sum >/dev/null || cmd="shasum -a 256"
  $cmd "$1" | cut -d' ' -f1
}

# Load packages
source "${openwrt_dir}/packages"

# Load spec
[ $# -eq '0' ] && { print_usage; exit 1; }
spec=$1
spec_file="${openwrt_dir}/specs/${spec}"
echo "Load ${spec_file} ..."
source ${spec_file} || { print_usage; exit 1; }

# Check spec
num=0
for x in OW_VERSION OW_TARGET OW_SUBTARGET IMAGEBUILDER_HASH; do
  [ "a" == "a${!x}" ] && { echo $x has NO value!; num=$(( $num + 1 )); }
done
[ $num -gt '0' ] && exit 1

#
build_dir="${openwrt_dir}/build"
build_spec_dir="${build_dir}/${spec}"
bin_dir="${build_dir}/dl_${OW_VERSION}_${OW_TARGET}_${OW_SUBTARGET}"
mirror_url="${MIRROR_URL:-https://downloads.openwrt.org}"
target_url="${mirror_url}/releases/${OW_VERSION}/targets/${OW_TARGET}/${OW_SUBTARGET}"
pkg_url="${mirror_url}/releases/${OW_VERSION}/packages/${OW_ARCH}_${OW_CPU_TYPE}"${OW_CPU_SUBTYPE:+"_${OW_CPU_SUBTYPE}"}
IMAGEBUILDER=openwrt-imagebuilder-${OW_VERSION}-${OW_TARGET}-${OW_SUBTARGET}.Linux-x86_64.tar.xz
IMAGEBUILDER_DIR=${IMAGEBUILDER%.tar.xz}
IMAGEBUILDER_URL="${target_url}/${IMAGEBUILDER}"

# PACKAGES
packages=""
for pkg in "${PACKAGES[@]}"; do
	pkg_var=PACKAGES_${pkg}
	packages="${packages} "`echo ${!pkg_var}`
done
packages="${packages} "`echo ${PACKAGES_EXT}`

# Prepare building
mkdir -p "${build_dir}"
cd "${build_dir}"

# Download & unarchive Image Builder
if [ ! -f "${IMAGEBUILDER}" ] || [ "${IMAGEBUILDER_HASH}" != "$( check_hash ${IMAGEBUILDER} )" ]; then
  # Remove old files
  [ -e ${build_spec_dir} ] && rm -rf ${build_spec_dir}
  [ -f ${IMAGEBUILDER} ] && rm ${IMAGEBUILDER}
  # Download
  echo "Downloading ${IMAGEBUILDER_URL} ..."
  curl -# -O ${IMAGEBUILDER_URL} || exit 1
  [ "${IMAGEBUILDER_HASH}" != "$( check_hash ${IMAGEBUILDER} )" ] && { echo "HASH NOT matches!"; exit 1; }
fi

# Unarchive
if [ ! -e ${build_spec_dir} ]; then
  [ -e ${IMAGEBUILDER_DIR} ] && rm -rf ${IMAGEBUILDER_DIR}
  echo "Unarchive ${IMAGEBUILDER} ..."
  tar xJf ${IMAGEBUILDER} && mv ${IMAGEBUILDER_DIR} ${build_spec_dir}
fi

#
cd ${build_spec_dir}
# Clean up
rm -rf dl
rm -rf files

# dl -> ../dl
mkdir -p "${bin_dir}"
ln -s "${bin_dir}" dl

# repositories.conf
echo "Generate repositories.conf ..."
mv repositories.conf repositories.conf.bak
for repo in "${CUSTOM_REPOSITORIES[@]}"; do
  echo ${repo} >> repositories.conf
done
echo "src/gz openwrt_core ${target_url}/packages" >> repositories.conf
for repo in "base" "luci" "packages" "routing" "telephony"; do
  echo "src/gz openwrt_${repo} ${pkg_url}/${repo}" >> repositories.conf
done
echo "src imagebuilder file:packages" >> repositories.conf

# files
echo "Copy files ..."
mkdir -p files
for x in "${FILES[@]}"; do
  cp -f -R -v "${openwrt_dir}/files/$x"/* files/
done

# make image
echo "Generate images ..."
eval make image ${FILES:+"FILES=files"} ${OW_PROFILE:+"PROFILE=${OW_PROFILE}"} ${packages:+"PACKAGES=\"${packages}\""}
